In [7]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [8]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\homepricesohe.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [9]:
dummy = pd.get_dummies(df.town)
dummy

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [10]:
dummy = dummy.drop(['west windsor'] ,axis = 'columns')
dummy

    monroe township  robinsville
0              True        False
1              True        False
2              True        False
3              True        False
4              True        False
5             False        False
6             False        False
7             False        False
8             False        False
9             False         True
10            False         True
11            False         True
12            False         True

In [11]:
merged = pd.concat([df,dummy],axis = 'columns')
merged

               town  area   price  monroe township  robinsville
0   monroe township  2600  550000             True        False
1   monroe township  3000  565000             True        False
2   monroe township  3200  610000             True        False
3   monroe township  3600  680000             True        False
4   monroe township  4000  725000             True        False
5      west windsor  2600  585000            False        False
6      west windsor  2800  615000            False        False
7      west windsor  3300  650000            False        False
8      west windsor  3600  710000            False        False
9       robinsville  2600  575000            False         True
10      robinsville  2900  600000            False         True
11      robinsville  3100  620000            False         True
12      robinsville  3600  695000            False         True

In [12]:
final = merged.drop(['town'],axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [13]:
x = final.drop(['price'],axis='columns')
x

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [14]:
y = final['price']
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [15]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown = 'ignore')
ohe

OneHotEncoder(handle_unknown='ignore')

In [16]:
x1 = ohe.fit_transform(df[['town']])
x1 = pd.DataFrame(x1.toarray())
x1

      0    1    2
0   1.0  0.0  0.0
1   1.0  0.0  0.0
2   1.0  0.0  0.0
3   1.0  0.0  0.0
4   1.0  0.0  0.0
5   0.0  0.0  1.0
6   0.0  0.0  1.0
7   0.0  0.0  1.0
8   0.0  0.0  1.0
9   0.0  1.0  0.0
10  0.0  1.0  0.0
11  0.0  1.0  0.0
12  0.0  1.0  0.0

In [18]:
x1 = x1.iloc[:,1:]
x1

      1    2
0   0.0  0.0
1   0.0  0.0
2   0.0  0.0
3   0.0  0.0
4   0.0  0.0
5   0.0  1.0
6   0.0  1.0
7   0.0  1.0
8   0.0  1.0
9   1.0  0.0
10  1.0  0.0
11  1.0  0.0
12  1.0  0.0

In [20]:
x = pd.concat([x,x1],axis = "columns")
x

    area  monroe township  robinsville    1    2    1    2
0   2600             True        False  0.0  0.0  0.0  0.0
1   3000             True        False  0.0  0.0  0.0  0.0
2   3200             True        False  0.0  0.0  0.0  0.0
3   3600             True        False  0.0  0.0  0.0  0.0
4   4000             True        False  0.0  0.0  0.0  0.0
5   2600            False        False  0.0  1.0  0.0  1.0
6   2800            False        False  0.0  1.0  0.0  1.0
7   3300            False        False  0.0  1.0  0.0  1.0
8   3600            False        False  0.0  1.0  0.0  1.0
9   2600            False         True  1.0  0.0  1.0  0.0
10  2900            False         True  1.0  0.0  1.0  0.0
11  3100            False         True  1.0  0.0  1.0  0.0
12  3600            False         True  1.0  0.0  1.0  0.0

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model
model.fit(x,y)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.